// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 15/08/2026, 22.23.01
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["D:/MyProject/NexEo/apps/frontend-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/MyProject/NexEo/apps/frontend-nuxt/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/MyProject/NexEo/apps/frontend-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/MyProject/NexEo/apps/frontend-nuxt/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/MyProject/NexEo/apps/frontend-nuxt/plugins/**/*.{js,ts,mjs}","D:/MyProject/NexEo/apps/frontend-nuxt/composables/**/*.{js,ts,mjs}","D:/MyProject/NexEo/apps/frontend-nuxt/utils/**/*.{js,ts,mjs}","D:/MyProject/NexEo/apps/frontend-nuxt/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/MyProject/NexEo/apps/frontend-nuxt/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/MyProject/NexEo/apps/frontend-nuxt/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/MyProject/NexEo/apps/frontend-nuxt/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;