// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/categories': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/categories.get').default>>>>
    }
    '/api/download/:filename': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/download/[filename].get').default>>>>
    }
    '/api/downloader/tasks': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/downloader/tasks.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/downloader/tasks.post').default>>>>
    }
    '/api/downloader/tasks/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/downloader/tasks/[id].delete').default>>>>
    }
    '/api/downloader/tasks/:id/cancel': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/downloader/tasks/[id]/cancel.post').default>>>>
    }
    '/api/info': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/info.get').default>>>>
    }
    '/api/manga/:slug': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/manga/[slug].get').default>>>>
    }
    '/api/manga/:slug/chapter/:chapter': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/manga/[slug]/chapter/[chapter].get').default>>>>
    }
    '/api/manga/:slug/chapter/:chapter/export': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/manga/[slug]/chapter/[chapter]/export.get').default>>>>
    }
    '/api/manga/:slug/chapters': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/manga/[slug]/chapters.get').default>>>>
    }
    '/api/manga/library': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/manga/library.get').default>>>>
    }
    '/api/manga/online/detail': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/manga/online/detail.get').default>>>>
    }
    '/api/manga/online/download': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/manga/online/download.post').default>>>>
    }
    '/api/manga/online/search': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/manga/online/search.get').default>>>>
    }
    '/api/novel/:slug': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/novel/[slug].get').default>>>>
    }
    '/api/novel/:slug/chapter/:filename': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/novel/[slug]/chapter/[filename].get').default>>>>
    }
    '/api/novel/:slug/chapters': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/novel/[slug]/chapters.get').default>>>>
    }
    '/api/novel': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/novel/index.get').default>>>>
    }
    '/api/novel/library': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/novel/library.get').default>>>>
    }
    '/api/novels/:slug': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/novels/[slug].get').default>>>>
    }
    '/api/novels/:slug/chapter/:filename': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/novels/[slug]/chapter/[filename].get').default>>>>
    }
    '/api/novels/:slug/chapters': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/novels/[slug]/chapters.get').default>>>>
    }
    '/api/novels/:slug/export-epub': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/novels/[slug]/export-epub.get').default>>>>
    }
    '/api/novels/:slug/export': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/novels/[slug]/export.get').default>>>>
    }
    '/api/novels/epub/import': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/novels/epub/import.post').default>>>>
    }
    '/api/novels/import': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/novels/import.post').default>>>>
    }
    '/api/novels/library': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/novels/library.get').default>>>>
    }
    '/api/novels/sources': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/novels/sources.get').default>>>>
    }
    '/api/novels/sources/:source/novel/:slug': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/novels/sources/[source]/novel/[slug].get').default>>>>
    }
    '/api/novels/sources/:source/novels': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/novels/sources/[source]/novels.get').default>>>>
    }
    '/api/novels/translate-all': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/novels/translate-all.post').default>>>>
    }
    '/api/novels/translate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/novels/translate.post').default>>>>
    }
    '/api/qrcode': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/qrcode.get').default>>>>
    }
    '/api/shared-files/:filename': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/shared-files/[filename].delete').default>>>>
    }
    '/api/shared-files/download/:filename': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/shared-files/download/[filename].get').default>>>>
    }
    '/api/shared-files': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/shared-files/index.get').default>>>>
    }
    '/api/shared-files/upload': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/shared-files/upload.post').default>>>>
    }
    '/api/thumbnails/**:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/thumbnails/[...id].get').default>>>>
    }
    '/api/thumbnails/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/thumbnails/[id].get').default>>>>
    }
    '/api/upload': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/upload.post').default>>>>
    }
    '/api/video/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/video/[id].get').default>>>>
    }
    '/api/video/:id/stream': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/video/[id]/stream.get').default>>>>
    }
    '/api/video/categories': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/video/categories.get').default>>>>
    }
    '/api/video/category/:category/folders': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/video/category/[category]/folders.get').default>>>>
    }
    '/api/video/folder/:folder/videos': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/video/folder/[folder]/videos.get').default>>>>
    }
    '/api/video/refresh': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/video/refresh.post').default>>>>
    }
    '/api/video/search': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/video/search.get').default>>>>
    }
    '/api/video/thumbnail/**:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/video/thumbnail/[...id].get').default>>>>
    }
    '/api/video/thumbnail/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/video/thumbnail/[id].get').default>>>>
    }
    '/api/youtube/download': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/youtube/download.post').default>>>>
    }
    '/api/youtube/info': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/youtube/info.post').default>>>>
    }
    '/_manga/**:path': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/_manga/[...path].get').default>>>>
    }
    '/_novels/**:path': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/_novels/[...path].get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxt+nitro-server@3.21.11__ab6b34050c574ac4ae20c7ed2556094e/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}